USE elearning;

-- Insert data to roles
INSERT INTO roles( name, description ) VALUES ("ROLE_ADMIN", "Quản trị hệ thống");
INSERT INTO roles( name, description ) VALUES ("ROLE_TEACHER", "Giáo viên");
INSERT INTO roles( name, description ) VALUES ("ROLE_USER", "Học viên");

-- Inser data to categories
insert into categories (title, icon) values ('Development', 'fa fa-laptop');
insert into categories (title, icon) values ('Photography', 'fa fa-camera-retro');
insert into categories (title, icon) values ('Business', 'fa fa-bar-chart');
insert into categories (title, icon) values ('IT & Software', 'fa fa-desktop');
insert into categories (title, icon) values ('Marketing', 'fa fa-handshake-o');
insert into categories (title, icon) values ('Music', 'fa fa-music');
insert into categories (title, icon) values ('Design', 'fa fa-pencil-square-o');
insert into categories (title, icon) values ('Cooking', 'fa fa-cutlery');

-- Insert data to users
-- password: 123456
insert into users (email, fullname, password, phone, address, role_id) values ('admin@gmail.com', 'Lê Phước Thiện', '$2a$10$/owwqZ6SWn5AAQr02xO3uOTIEMxzAxtEJsH4IlEl8IOIMVJLubT3C', '', '', 1);
insert into users (email, fullname, password, phone, address, role_id) values ('teacher_1@gmail.com', 'Wilone Menary', '$2a$10$/owwqZ6SWn5AAQr02xO3uOTIEMxzAxtEJsH4IlEl8IOIMVJLubT3C', '194-528-9732', '55334 Prairie Rose Parkway', 2);
insert into users (email, fullname, password, phone, address, role_id) values ('teacher_2@gmail.com', 'Marjy Cornhill', '$2a$10$/owwqZ6SWn5AAQr02xO3uOTIEMxzAxtEJsH4IlEl8IOIMVJLubT3C', '338-330-8921', '68 Gerald Place', 2);
insert into users (email, fullname, password, phone, address, role_id) values ('teacher_3@gmail.com', 'Natka Hiseman', '$2a$10$/owwqZ6SWn5AAQr02xO3uOTIEMxzAxtEJsH4IlEl8IOIMVJLubT3C', '873-178-2150', '184 Monterey Place', 2);
insert into users (email, fullname, password, phone, address, role_id) values ('hyate3@howstuffworks.com', 'Hoebart Yate', '$2a$10$/owwqZ6SWn5AAQr02xO3uOTIEMxzAxtEJsH4IlEl8IOIMVJLubT3C', '760-449-4620', '3389 Moulton Alley', 3);
insert into users (email, fullname, password, phone, address, role_id) values ('ckreber4@boston.com', 'Claudio Kreber', '$2a$10$/owwqZ6SWn5AAQr02xO3uOTIEMxzAxtEJsH4IlEl8IOIMVJLubT3C', '212-906-7846', '8870 Blue Bill Park Plaza', 3);
insert into users (email, fullname, password, phone, address, role_id) values ('wle5@google.ru', 'Woody Le Merchant', '$2a$10$/owwqZ6SWn5AAQr02xO3uOTIEMxzAxtEJsH4IlEl8IOIMVJLubT3C', '288-501-6552', '00602 Anderson Court', 3);
insert into users (email, fullname, password, phone, address, role_id) values ('asousa6@github.com', 'Adelaida Sousa', '$2a$10$/owwqZ6SWn5AAQr02xO3uOTIEMxzAxtEJsH4IlEl8IOIMVJLubT3C', '207-886-6028', '19 Stuart Trail', 3);
insert into users (email, fullname, password, phone, address, role_id) values ('rcarek7@skype.com', 'Rosemary Carek', '$2a$10$/owwqZ6SWn5AAQr02xO3uOTIEMxzAxtEJsH4IlEl8IOIMVJLubT3C', '177-609-0393', '6956 Summerview Court', 3);
insert into users (email, fullname, password, phone, address, role_id) values ('tferenczi8@nbcnews.com', 'Tedmund Ferenczi', '$2a$10$/owwqZ6SWn5AAQr02xO3uOTIEMxzAxtEJsH4IlEl8IOIMVJLubT3C', '694-424-6561', '8 Cody Trail', 3);
insert into users (email, fullname, password, phone, address, role_id) values ('alovelace9@shop-pro.jp', 'Arabele Lovelace', '$2a$10$/owwqZ6SWn5AAQr02xO3uOTIEMxzAxtEJsH4IlEl8IOIMVJLubT3C', '700-868-2727', '0 Ruskin Center', 3);

-- Insert data to courses
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Research Nurse', 170, 1656950, 18, 1358699, 8);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('VP Quality Control', 166, 4163578, 37, 2623054, 2);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Recruiting Manager', 67, 2497644, 11, 2222903, 6);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Computer Systems Analyst III', 155, 4270208, 21, 3373464, 5);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Nurse', 130, 3207728, 46, 1732173, 2);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Engineer IV', 169, 3281677, 43, 1870555, 4);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Design Engineer', 72, 2422213, 50, 1211106, 8);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Actuary', 177, 1801798, 46, 972970, 6);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Chief Design Engineer', 55, 3825880, 39, 2333786, 1);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Marketing Manager', 60, 3924780, 14, 3375310, 3);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Project Manager', 131, 1080629, 20, 864503, 7);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Dental Hygienist', 76, 3754751, 19, 3041348, 3);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Sales Associate', 107, 3013255, 37, 1898350, 3);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('General Manager', 96, 4663539, 22, 3637560, 1);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Structural Engineer', 179, 3236091, 47, 1715128, 6);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Dental Hygienist', 176, 1106048, 14, 951201, 2);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('VP Sales', 143, 3693672, 36, 2363950, 2);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Health Coach I', 52, 2397930, 12, 2110178, 1);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Marketing Manager', 69, 3438504, 35, 2235027, 7);
insert into courses (title, letures_count, price, discount, promotion_price, category_id) values ('Junior Executive', 94, 1628043, 20, 1302434, 4);

-- Inser data to user_courses
-- teacher
insert into user_courses (user_id, course_id, role_id) values (2, 1, 2);
insert into user_courses (user_id, course_id, role_id) values (3, 2, 2);
insert into user_courses (user_id, course_id, role_id) values (4, 3, 2);
insert into user_courses (user_id, course_id, role_id) values (2, 4, 2);
insert into user_courses (user_id, course_id, role_id) values (3, 5, 2);
insert into user_courses (user_id, course_id, role_id) values (4, 6, 2);
insert into user_courses (user_id, course_id, role_id) values (2, 7, 2);
insert into user_courses (user_id, course_id, role_id) values (3, 8, 2);
insert into user_courses (user_id, course_id, role_id) values (4, 9, 2);
insert into user_courses (user_id, course_id, role_id) values (2, 10, 2);
insert into user_courses (user_id, course_id, role_id) values (3, 11, 2);
insert into user_courses (user_id, course_id, role_id) values (4, 12, 2);
insert into user_courses (user_id, course_id, role_id) values (2, 13, 2);
insert into user_courses (user_id, course_id, role_id) values (3, 14, 2);
insert into user_courses (user_id, course_id, role_id) values (4, 15, 2);
insert into user_courses (user_id, course_id, role_id) values (2, 16, 2);
insert into user_courses (user_id, course_id, role_id) values (3, 17, 2);
insert into user_courses (user_id, course_id, role_id) values (4, 18, 2);
insert into user_courses (user_id, course_id, role_id) values (2, 19, 2);
insert into user_courses (user_id, course_id, role_id) values (3, 20, 2);
-- User
insert into user_courses (user_id, course_id, role_id) values (5, 1, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 1, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 1, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 1, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 1, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 2, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 2, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 2, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 2, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 2, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 3, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 3, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 3, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 3, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 3, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 4, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 4, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 4, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 4, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 4, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 5, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 5, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 5, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 5, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 5, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 6, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 6, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 6, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 6, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 6, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 7, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 7, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 7, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 7, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 7, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 8, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 8, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 8, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 8, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 8, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 9, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 9, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 9, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 9, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 9, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 10, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 10, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 10, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 10, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 10, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 11, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 11, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 11, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 11, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 11, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 12, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 12, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 12, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 12, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 12, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 13, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 13, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 13, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 13, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 13, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 14, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 14, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 14, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 14, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 14, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 15, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 15, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 15, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 15, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 15, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 16, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 16, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 16, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 16, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 16, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 17, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 17, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 17, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 17, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 17, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 18, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 18, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 18, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 18, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 18, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 19, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 19, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 19, 3);
insert into user_courses (user_id, course_id, role_id) values (7, 19, 3);
insert into user_courses (user_id, course_id, role_id) values (8, 19, 3);
insert into user_courses (user_id, course_id, role_id) values (9, 20, 3);
insert into user_courses (user_id, course_id, role_id) values (10, 20, 3);
insert into user_courses (user_id, course_id, role_id) values (11, 20, 3);
insert into user_courses (user_id, course_id, role_id) values (5, 20, 3);
insert into user_courses (user_id, course_id, role_id) values (6, 20, 3);



-- Insert data to target
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 6);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 3);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 12);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 13);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 15);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 20);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 20);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 14);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 13);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 16);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 10);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 9);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 1);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 18);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 17);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 1);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 4);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 3);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 1);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 12);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 11);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 4);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 3);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 16);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 3);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 7);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 19);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 11);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 6);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 12);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 3);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 5);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 5);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 7);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 7);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 20);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 8);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 2);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 17);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 17);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 3);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 2);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 15);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 20);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 4);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 11);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 14);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 19);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 11);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 12);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 5);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 5);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 19);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 11);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 19);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 12);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 11);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 16);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 10);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 5);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 3);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 20);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 7);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 2);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 16);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 20);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 17);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 5);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 8);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 18);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 9);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 7);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 19);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 3);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 17);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 10);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 18);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 13);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 15);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 7);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 1);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 11);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 13);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 19);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 18);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 9);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 9);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 9);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 19);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 12);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 2);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 5);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 19);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 3);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 10);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 12);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 2);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 10);
insert into targets (title, course_id) values ('Create games with Python, like Tic Tac Toe and Blackjack!', 10);
insert into targets (title, course_id) values ('Learn to use Python professionally, learning both Python 2 and Python 3!', 20);

-- Insert data to videos
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 15726, 9);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 4424, 1);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 59366, 3);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 199416, 11);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 12653, 14);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 199750, 13);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 127755, 13);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 187265, 20);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 118408, 11);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 176460, 11);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 22950, 1);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 22689, 14);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 77837, 16);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 12494, 11);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 84440, 20);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 43786, 11);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 192179, 11);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 51826, 8);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 148821, 19);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 14369, 14);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 68870, 11);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 147940, 1);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 209489, 9);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 154906, 12);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 86947, 13);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 63299, 7);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 35395, 6);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 108179, 18);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 184411, 20);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 29925, 5);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 98278, 8);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 178107, 19);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 77137, 19);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 151171, 19);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 62970, 4);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 98092, 7);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 16603, 6);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 60344, 1);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 83055, 9);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 136922, 20);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 115693, 5);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 172423, 20);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 205053, 15);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 78376, 19);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 150258, 7);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 75555, 19);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 114535, 19);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 18683, 13);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 191154, 3);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 163336, 11);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 210269, 20);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 110802, 13);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 129423, 11);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 123675, 12);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 151149, 10);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 59594, 8);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 159054, 20);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 63047, 7);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 52730, 3);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 197811, 9);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 84102, 19);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 154224, 6);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 213995, 18);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 105070, 14);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 81689, 3);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 78976, 20);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 110242, 16);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 96848, 20);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 43600, 12);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 108123, 19);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 158684, 4);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 93460, 14);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 215743, 9);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 211498, 9);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 132479, 15);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 28748, 17);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 148450, 10);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 55389, 17);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 93467, 9);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 144468, 8);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 89443, 20);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 174287, 15);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 11381, 2);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 210196, 11);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 86280, 8);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 118906, 4);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 39748, 12);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 141289, 2);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 36780, 19);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 113726, 3);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 37861, 9);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 44152, 2);
insert into videos (title, url, time_count, course_id) values ('Course Introduction', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 9096, 8);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 203835, 13);
insert into videos (title, url, time_count, course_id) values ('Introduction to Python Data Types', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 92813, 9);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 38989, 6);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 213295, 8);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 183691, 3);
insert into videos (title, url, time_count, course_id) values ('Git and Github Overview (Optional)', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 9978, 2);
insert into videos (title, url, time_count, course_id) values ('Getting the Notebooks and the Course Material', 'https://www.youtube.com/embed/ODeB1CShkT4?si=P-vSDJmLrIKHp0gQ', 20225, 4);



